### ISSUE TITLE
open-source timestamp correction nodelet and arduino/teensy sketch?

### ISSUE THREAD

**Issue by tuandle** [leggedrobotics/hardware_time_sync#3]
Hi @raabuchanan ,
Thank you for open source the guideline.
I wonder if there is any plan to open source the timestamp correction nodelet and arduino/teensy sketch? That's gonna be a huge help for a beginner at hardware setup like me :)
Thanks again!

**Comment by raabuchanan** [comment]
Hi @tuandle ,
At the moment we have no plans to open source the code. If you're looking for a starting point take a look at [this tutorial](http://grauonline.de/wordpress/?page_id=1951) which uses an Arduino to synchronize an IMU and camera. Other than that we may add some example scripts or code snippets to demonstrate which libraries we're using.
Hope that help,
Russell

**Comment by tuandle** [comment]
Thanks for your tip!
